add common schema for firepit
IBM/firepit pull request #38
Opened 2021-10-21 12:19 UTC by charliewutw1

This PR contains to create a common schema for two functions  `match` and `in_subnet`

2021-10-21 12:40 UTC, pcoccoli requested changes

2021-10-21 12:40 UTC, pcoccoli commented on firepit/pgstorage.py
> +            self._execute(f'CREATE SCHEMA IF NOT EXISTS "firepit_common";')
You don't need an f-string here.
If the schema *does* exist, will this raise an exception?  We only need to create this once, so we need a way to check if the schema already exists and don't bother creating it if it does.

2021-10-21 12:40 UTC, pcoccoli commented on firepit/pgstorage.py
> +            self._execute(f'CREATE SCHEMA IF NOT EXISTS "firepit_common";')
Something like the `SELECT (EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES...` that we do for the session schema to decide if we should call `_setup()`.

2021-10-25 11:34 UTC, charliewutw1 commented
attached unit test report against local postgres

```

$ FIREPITDB="postgresql://charlie:c1234@localhost:5432/stixdata" pytest
=============================================================================================== test session starts ================================================================================================                                                                                                                                                                                             

tests/test_custom_objects.py .                                                                                                                                                                               [  0%]
tests/test_errors.py ..................                                                                                                                                                                      [ 13%]
tests/test_props.py ..............................                                                                                                                                                           [ 36%]
tests/test_query.py .......................................                                                                                                                                                  [ 64%]
tests/test_storage.py ..................................... 
tests/test_validate.py ........... 
   ```

2021-10-25 11:36 UTC, pcoccoli approved these changes
Looks good

2021-10-25 11:41 UTC, merged